dy:
  auth:
    public-key-path: classpath:public.key
  web-security:
    permissions:
      - /actuator/health
    cors:
      enabled: true
      allowed-methods: GET,POST,PUT,DELETE
      allow-credentials: true
      max-age: 2h