bw:
  auth:
    public-key-path: classpath:public.key
  web-security:
    permissions:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE, OPTIONS
      allowed-headers: "*"
      allow-credentials: false
      max-age: 2h